apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: mernapp
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: pranaynamburu91/backend:v1
        env:
        - name: MONGODB_URL
          value: mongodb://database-service:27017/bookstore
        ports:
        - containerPort: 5555