services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    restart: always
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    networks:
      - frontend_network
    depends_on:
      - backend
    command: npm run dev -- --host 0.0.0.0
  backend:
    build:
      context: ./backend
    container_name: backend
    ports: 
      - "5555:5555"
    restart: always
    volumes:
     - ./backend:/app
      - backend_node_modules:/app/node_modules
    networks:
      - backend_network
  db:
    image: mongo:7
    container_name: db
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - db_data:/data/db
    networks:
      - backend_network
volumes:
  frontend_node_modules:
  backend_node_modules:
  db_data:
networks:
  frontend_network:
    driver: bridge
  backend_network:
    driver: bridge