apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-mongo
  namespace: mernapp
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: pranaynamburu91/mongodb:v1.0
        ports:
        - containerPort: 27017